### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Legolii** [XYZliang/HUAWEI-STORE-GO#5]
@XYZliang 
你好我在用30epro做测试的时候发现报错

> COLOR = '亮黑色'

> EDITION = '5G全网通 256GB'

> COMBO = '官方标配'

颜色选择错误！请手动选择！
版本选择错误！请手动选择！
套餐选择错误！请手动选择！
2021-02-24 16:46:1215502188239准备完毕，开始等待
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\python3.8.8\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\python3.8.8\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/LEgo1/Desktop/HUAWEI-STORE-GO-main (1)/HUAWEI-STORE-GO-main/HUAWEI STORE GO.py", line 324, in loginMall
    goToBuy(driver, user)
  File "C:/Users/LEgo1/Desktop/HUAWEI-STORE-GO-main (1)/HUAWEI-STORE-GO-main/HUAWEI STORE GO.py", line 178, in goToBuy
    text = driver.find_elements_by_xpath(
IndexError: list index out of range

Process finished with exit code 0

**Comment by XYZliang** [comment]
我在Windows测试的时候也偶尔会出现这个情况。。查找元素失败了。。。因为暂时没有好的解决办法就没有改动。
下次有空我想想办法。
那就暂时只能手动选择配置了～

**Comment by XYZliang** [comment]
应该是登陆的毛病。已经在v3.2修复
