### ISSUE TITLE
发生报错

### ISSUE THREAD

**Issue by Broomhildall** [XYZliang/HUAWEI-STORE-GO#6]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "HUAWEI STORE GO.py", line 324, in loginMall
    goToBuy(driver, user)
  File "HUAWEI STORE GO.py", line 178, in goToBuy
    text = driver.find_elements_by_xpath(
IndexError: list index out of range

**Comment by Jennyhjy** [comment]
我是在登陆的时候，显示正确登陆了，但实际上进入身份验证了，却没有走身份验证的逻辑，导致后面网页跳转回了登陆界面，报了获取不到元素的错。

**Comment by XYZliang** [comment]
> 我是在登陆的时候，显示正确登陆了，但实际上进入身份验证了，却没有走身份验证的逻辑，导致后面网页转向回了登陆界面，报了获取不到元素的错。

是的，我注意到了，当时比较匆忙改错了，会尽快修复

**Comment by XYZliang** [comment]
已经在V3.2修复
