### ISSUE TITLE
排队完到订单确认的界面报错，浏览器自动关闭

### ISSUE THREAD

**Issue by highning** [XYZliang/HUAWEI-STORE-GO#8]
D:\Python\Python39\python.exe "E:/Downloads/软件/huaweitest/HUAWEI-STORE-GO-main/HUAWEI STORE GO.py"
highning@163.com成功输入了账号密码，尝试登陆.
highning@163.com请手动完成认证并登陆！
请输入图形验证码
highning@163.com验证码已经发送至136******80
2021-02-26 20:02:54highning@163.com登录成功！！
highning@163.com打开购买页面
highning@163.com亮黑色选择成功！
highning@163.com5G全网通 8GB+128GB选择成功！
highning@163.com官方标配选择成功！
2021-02-26 20:03:02highning@163.com准备完毕，开始等待
2021-02-26 20:03:02highning@163.com未到脚本开启时间，请选择好抢购的颜色、版本、套餐等(若已经配置则忽略)，将在设定的脚本启动时间前15秒启动
--------------------------------------------------------------------------------------------
2021-02-26 20:04:35highning@163.com即将开始抢购，程序启动
2021-02-26 20:04:50highning@163.com可以开始申购，立即申购
highning@163.com开始排队：2021-02-26 20:04:50
2021-02-26 20:04:51highning@163.com:排队中
2021-02-26 20:04:51highning@163.com:排队中
2021-02-26 20:04:52highning@163.com:排队中
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Downloads\软件\huaweitest\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 342, in loginMall
    goToBuy(driver, user)
  File "E:\Downloads\软件\huaweitest\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 227, in goToBuy
    onQueue(driver, user)
  File "E:\Downloads\软件\huaweitest\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 75, in onQueue
    errorbutton = driver.find_element_by_id("boxCloseBtn")
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="boxCloseBtn"]"}
  (Session info: chrome=88.0.4324.182)

Process finished with exit code 0

win10+python3.9.1+Chrome  88.0.4324.182

**Comment by XYZliang** [comment]
排队成功后进行下单的代码是原来项目留下的我没怎么改动，可能会有问题。。
因为我这么久就没成功抢到过，没进过下单页面没法去修复哈哈。。
我尽量修复

**Comment by highning** [comment]
> 排队成功后进行下单的代码是原来项目留下的我没怎么改动，可能会有问题。。
> 因为我这么久就没成功抢到过，没进过下单页面没法去修复哈哈。。
> 我尽量修复

**3.2版本问题依旧存在**

2021-03-03 10:06:45highning@163.com即将开始抢购，程序启动
2021-03-03 10:07:59highning@163.com可以开始申购，立即申购
highning@163.com开始排队：2021-03-03 10:07:00
2021-03-03 10:08:00highning@163.com:排队中
2021-03-03 10:08:01highning@163.com:排队中
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Downloads\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 324, in loginMall
    goToBuy(driver, user)
  File "E:\Downloads\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 246, in goToBuy
    onQueue(driver, user)
  File "E:\Downloads\HUAWEI-STORE-GO-main\HUAWEI STORE GO.py", line 77, in onQueue
    errorbutton = driver.find_element_by_id("boxCloseBtn")
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="boxCloseBtn"]"}
  (Session info: chrome=88.0.4324.190)


Process finished with exit code 0


到了订单确认界面后浏览器闪退，想手动确认订单都做不到了

**Comment by highning** [comment]
debug到  if BUY_URL == driver.current_url:  这一步就闪退了，没有进入后面的代码
```
def submitOrder(driver, user):
    time.sleep(1)
    if BUY_URL == driver.current_url:
`````

**Comment by XYZliang** [comment]
> debug到if BUY_URL == driver.current_url：这一步就闪退了，没有进入后面的代码
> 
> ```
> def submitOrder(driver, user):
>     time.sleep(1)
>     if BUY_URL == driver.current_url:
> ```

这个在3.3版本已经修复了，建议下载最新的脚本看看哦

**Comment by highning** [comment]
> > debug到if BUY_URL == driver.current_url：这一步就闪退了，没有进入后面的代码
> > ```
> > def submitOrder(driver, user):
> >     time.sleep(1)
> >     if BUY_URL == driver.current_url:
> > ```
> 
> 这个在3.3版本已经修复了，建议下载最新的脚本看看哦

没看到3.3的版本啊。。。

**Comment by CainLuo** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cainluo/Desktop/Personal Project/HUAWEI-STORE-GO/HUAWEI STORE GO.py", line 324, in loginMall
    goToBuy(driver, user)
  File "/Users/cainluo/Desktop/Personal Project/HUAWEI-STORE-GO/HUAWEI STORE GO.py", line 178, in goToBuy
    text = driver.find_elements_by_xpath(
IndexError: list index out of range

貌似我也遇到这个问题了 @XYZliang

**Comment by highning** [comment]
> > debug到if BUY_URL == driver.current_url：这一步就闪退了，没有进入后面的代码
> > ```
> > def submitOrder(driver, user):
> >     time.sleep(1)
> >     if BUY_URL == driver.current_url:
> > ```
> 
> 这个在3.3版本已经修复了，建议下载最新的脚本看看哦

**3.3的版本还没有出哦，怎么下载？** @XYZliang

**Comment by XYZliang** [comment]
说错了，3.2版。一样直接下载仓库就是

**Comment by highning** [comment]
> 说错了，3.2版。一样直接下载仓库就是

3.2版本还是有同样的问题

**Comment by superwars** [comment]
请问老哥们这个问题现在解决了吗？

**Comment by XYZliang** [comment]
> 请问老哥们这个问题现在解决了吗？

我尝试过修复。。。。可是我没有抢成功过。。
